version: '3.9'
services:
  kafka:
    image: landoop/fast-data-dev:2.6.2
    container_name: kafka
    ports:
      - 2181:2181 # zookeeper
      - 3030:3030 # ui
      - 9092:9092 # broker
      - 8081:8081 # schema registry
      - 8082:8082 # rest proxy
      - 8083:8083 # kafka connect
    environment:
      - ADV_HOST=localhost
      - SAMPLEDATA=0
      - RUNNING_SAMPLEDATA=0
      - RUNTESTS=0
      - FORWARDLOGS=0
      - DISABLE_JMX=1
      - DEBUG=1
      - SUPERVISORWEB=0