language: go

go:
  - "1.12.x"

notifications:
 email: false

before_install:
 - go get github.com/mattn/goveralls

script:
 - go get -t -u ./...
 - make build
 - make test
 - $GOPATH/bin/goveralls -service=travis-ci