version: 2.1
jobs:
  quality-gate:
    docker:
      - image: 'cimg/go:1.19'
    steps:
      - checkout
      - run:
          name: Install
          command: make install
      - run:
          name: Build
          command: make build
      - run:
          name: Test
          command: make test
workflows:
  version: 2
  quality-gate:
    jobs:
      - quality-gate:
          context: dev
