version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.6
jobs:
  build-1:
    docker:
      - image: 'circleci/golang:1.17'
    steps:
      - checkout
      - run:
          name: Install
          command: make install
      - run:
          name: Build
          command: make build
      - run:
          name: Test
          command: make test
      - coveralls/upload:
          parallel: false
          token: ${COVERALLS_REPO_TOKEN}

workflows:
  version: 2
  coveralls_workflow:
    jobs:
      - build-1:
          context: dev
