version: 2.1

orbs:
  go: circleci/go@1.7.1
  ric-orb: ricardo/ric-orb@7

workflows:
  version: 2

  build-test:
    jobs:
      - ric-orb/quality_gate_job:
          name: 'quality-gate'
          context: dev
          executor: go-bullseye

      - ric-orb/codeql:
          context: dev
          executor: go-bullseye
          language: go
          requires:
          - quality-gate

executors:
  go-bullseye:
    docker:
      - image: docker.io/golang:1.20-bullseye
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_PASSWORD