version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.6
jobs:
  quality-gate:
    docker:
      - image: 'cimg/go:1.19'
    steps:
      - checkout
      - run:
          name: Install
          command: make install
      - run:
          name: Build
          command: make build
      - run:
          name: Test
          command: make test
      - run:
          name: install coveralls
          command: go install github.com/mattn/goveralls@latest
      - run:
          name: code coverage
          command: goveralls -service=circle-ci -ignore "mocks/*" -repotoken=$COVERALLS_REPO_TOKEN
workflows:
  version: 2
  coveralls_workflow:
    jobs:
      - quality-gate:
          context: dev
