name: Go Kafka Build and Test
run-name: Go Kafka Build and Test by ${{ github.actor }} on ${{ github.ref_name }}

on:
  push:
    branches:
      - master
    
  pull_request:

jobs:
  quality-gate:
    uses: ricardo-ch/golang-workflows/.github/workflows/library.yml@v1
    secrets: inherit

 